run:
  build-tags:
    - integration
  timeout: 5m
linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/sand8080/goxecutor
linters:
  enable:
    - govet
    - goimports
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - depguard
    - nakedret
    - prealloc
    - gocritic
    - exportloopref
    - bodyclose
    - durationcheck
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
